Update /users/followings & /users/followers APIs
xfrocks/bdApi pull request #125
Opened 2020-05-11 16:14 UTC by huynhtehoa

* Update GET /users/:userId/followers & /users/:userId/followings
* Allow ordering by follow_date (DESC/ASC)
* Support pagination

* Asana: https://app.asana.com/0/0/1175037401419894/f

2020-05-11 16:17 UTC, huynhtehoa commented
@datbth ơi. a trả thêm cái `users_total` để FE tính limit, page á. còn cái param `total` a vẫn để đó tại không biết có chỗ nào đang xài gì hông

2020-05-12 06:55 UTC, datbth reviewed
giữ behavior order mặc định là user_id như cũ đi anh

2020-05-12 12:50 UTC, huynhtehoa commented
> giữ behavior order mặc định là user_id như cũ đi anh

Updated em

2020-05-12 15:54 UTC, daohoangson commented
Cái `order` coi các method khác nó gom vô chung param không tách riêng param direction nha. Default bao giờ cũng là `natural`, còn nếu các order khác thì sẽ tương ứng theo key khi trả về, thêm hậu tố nếu là ngược chiều. Ví dụ `thread_create_date`, `thread_create_date_reverse` etc.

2020-05-15 13:20 UTC, huynhtehoa commented
> Cái `order` coi các method khác nó gom vô chung param không tách riêng param direction nha. Default bao giờ cũng là `natural`, còn nếu các order khác thì sẽ tương ứng theo key khi trả về, thêm hậu tố nếu là ngược chiều. Ví dụ `thread_create_date`, `thread_create_date_reverse` etc.

Dạ ukie anh. Em có update lại, anh review lại giúep em nha. Thanks anh Sơn

2020-05-16 17:37 UTC, daohoangson commented
Có vẻ ổn á, mà coi lại 2 điểm:

1. Chắc bỏ cái in request check cho total, giờ luôn trả lại field đó rồi. 
2. Confirm lại design xem screen này có cần full user data không (e.g. avatar?), nếu có thì chuyển qua xài search api để trả về user data luôn. Vẫn giữ pagination.

2020-05-19 14:35 UTC, huynhtehoa commented
> Có vẻ ổn á, mà coi lại 2 điểm:
> 
> 1. Chắc bỏ cái in request check cho total, giờ luôn trả lại field đó rồi.
> 2. Confirm lại design xem screen này có cần full user data không (e.g. avatar?), nếu có thì chuyển qua xài search api để trả về user data luôn. Vẫn giữ pagination.

Em có bỏ in request check với update lại code để dùng search API á a. Anh review lại giúp em nha

2020-05-19 14:45 UTC, datbth commented on xenforo/library/bdApi/ControllerApi/User.php
> +            array(),
chỗ này hình như phải bỏ `$user` vô nó mới gen ra mấy cái link `next`, `prev` đúng

2020-05-19 14:58 UTC, huynhtehoa commented on xenforo/library/bdApi/ControllerApi/User.php
> +            array(),
mấy link đó là sao zạ

2020-05-19 15:15 UTC, datbth commented on xenforo/library/bdApi/ControllerApi/User.php
> +            array(),
trong field `links` của response á  
![image](https://user-images.githubusercontent.com/15865062/82344399-36f5db80-9a1e-11ea-9957-4dc1d687612a.png)

2020-05-19 16:09 UTC, huynhtehoa commented on xenforo/library/bdApi/ControllerApi/User.php
> +            array(),
à. a dùng `array()` thì thấy vẫn có á

2020-05-19 16:50 UTC, daohoangson commented on xenforo/library/bdApi/ControllerApi/User.php
> +            array(),
Vẫn ra link mà link bị sai á. Thay vì `users/123/followers` thì nó sẽ chỉ là `users/followers` do link data không có.

2020-05-20 01:30 UTC, huynhtehoa commented on xenforo/library/bdApi/ControllerApi/User.php
> +            array(),
ah. ukie a. e có thêm `$user` vào rồi á

2020-05-20 03:43 UTC, daohoangson requested changes
Nếu đã cho order theo follow date thì data trả về kèm theo `follow_date` luôn nha.

2020-05-20 03:43 UTC, daohoangson commented on xenforo/library/bdApi/Extend/Model/User.php
> +    public function bdApi_getUsersFollowingUserId($userId, $fetchOptions = array())
Mấy hàm `bdApi_` này không liên quan gì với `XenForo_Model_User` thế nên tạo model `bdApi_Model_User` mới rồi di qua bên đó ha.

2020-05-20 03:43 UTC, daohoangson commented on xenforo/library/bdApi/Extend/Model/User.php
> +			SELECT user.*
Chỗ này SELECT `user_id` chắc đủ rồi hén.

2020-05-20 05:48 UTC, huynhtehoa commented on xenforo/library/bdApi/Extend/Model/User.php
> +			SELECT user.*
Updated anh. Em có thêm `follow_date` để có thể trả kèm á

2020-05-20 05:48 UTC, huynhtehoa commented on xenforo/library/bdApi/Extend/Model/User.php
> +    public function bdApi_getUsersFollowingUserId($userId, $fetchOptions = array())
Updated anh. Em có di 3 functions mới tạo trong PR này qua `bdApi_Model_User` á

2020-05-20 05:49 UTC, huynhtehoa reviewed
> Nếu đã cho order theo follow date thì data trả về kèm theo `follow_date` luôn nha.

Updated anh

2020-05-20 08:52 UTC, daohoangson requested changes
Giờ đang fetch all rồi mới slice lại theo page. Cái này chắc model fetch theo page ngay từ đầu thì an toàn hơn ha. Đề phòng mấy user có nhiều followers kiểu cuhiep / duyluan á.

Còn lại anh thấy okie rồi 👍

2020-05-20 11:18 UTC, huynhtehoa commented
> Giờ đang fetch all rồi mới slice lại theo page. Cái này chắc model fetch theo page ngay từ đầu thì an toàn hơn ha. Đề phòng mấy user có nhiều followers kiểu cuhiep / duyluan á.
> 
> Còn lại anh thấy okie rồi

Dạ ukie. Updated nha anh

2020-05-25 12:12 UTC, huynhtehoa commented
Anh @daohoangson khi nào rãnh review lại giúp em nhé

2020-06-04 06:04 UTC, daohoangson commented
Sau mấy commits gần đây cái PR này đã test lại chưa?

2020-06-04 12:02 UTC, huynhtehoa commented
> Sau mấy commits gần đây cái PR này đã test lại chưa?

Em vừa test lại thì thấy vẫn ổn á

2020-06-04 15:18 UTC, daohoangson requested changes
Ổn rồi á, refactor cái `bdApi_countUsersBeingFollowedByUserId` qua model riêng luôn cho gọn ha.

2020-06-04 15:46 UTC, huynhtehoa commented
> Ổn rồi á, refactor cái `bdApi_countUsersBeingFollowedByUserId` qua model riêng luôn cho gọn ha.

Dạ updated nha anh

2020-06-05 02:12 UTC, merged