include like_users info in Post data
xfrocks/bdApi pull request #126
Opened 2020-05-16 06:15 UTC by datbth

2020-05-16 09:19 UTC, daohoangson commented
Request thêm user cũng hơi căng đấy nhỉ, vì thread view số lượng lớn, mỗi page thì cũng nhiều like user. Design yêu cầu phải có avatar huh?

2020-05-16 17:32 UTC, daohoangson requested changes

2020-05-16 17:32 UTC, daohoangson commented on xenforo/library/bdApi/ControllerApi/Post.php
> +    /**
Cái này có vẻ không xài nữa, xoá?

2020-05-16 17:32 UTC, daohoangson commented on xenforo/library/bdApi/ControllerApi/Post.php
> +                    'links' => array(
Nếu trả về nhiều data thế này chắc phải hỗ trợ pagination + xài search api để trả về user data cho thống nhất ha.

2020-05-17 03:25 UTC, datbth commented on xenforo/library/bdApi/ControllerApi/Post.php
> +    /**
dạ đã xóa

2020-05-17 03:25 UTC, datbth commented on xenforo/library/bdApi/ControllerApi/Post.php
> +                    'links' => array(
dạ đã chỉnh lại

2020-05-17 03:26 UTC, datbth commented
đoạn fetch like đang dùng `getContentLikes` nó inner join hơi nhiều info của user. Có nên viết hàm mới fetch mỗi `liked_content` thôi không anh?

2020-05-18 02:48 UTC, daohoangson approved these changes

2020-05-18 02:49 UTC, daohoangson commented
> đoạn fetch like đang dùng getContentLikes nó inner join hơi nhiều info của user. Có nên viết hàm mới fetch mỗi liked_content thôi không anh?

Òh, cũng hay đó 👍

À mà cái like date có cần không hén? Thấy trả về, nếu không cần trên giao diện chắc cũng hạn chế mấy thông tin internal đó.

2020-05-18 03:46 UTC, datbth commented
dạ thấy bảo cần trên group telegram Xen Dev á anh  
![image](https://user-images.githubusercontent.com/15865062/82172551-aec7e700-98f4-11ea-8a17-6dcc5a5c41d6.png)

hàm mới bỏ vô Extend_Model_Post để fetch liked_content cho mỗi post thôi, hay là extend thêm Model_Like anh nhỉ?

2020-05-18 03:49 UTC, daohoangson commented
> hàm mới bỏ vô Extend_Model_Post để fetch liked_content cho mỗi post thôi, hay là extend thêm Model_Like anh nhỉ?

Làm hẳn cái model mới bdApi_Model_Like cho máu. Vì nó cũng chỉ 1 query có offset nên không cần extend luôn ha. À check nếu XenForo_Model_Like đã extend sẵn rồi thì quăng vô luôn cũng được. Còn chưa extend thì tạo mới hén.

2020-05-18 13:35 UTC, datbth commented
> > hàm mới bỏ vô Extend_Model_Post để fetch liked_content cho mỗi post thôi, hay là extend thêm Model_Like anh nhỉ?
> 
> Làm hẳn cái model mới bdApi_Model_Like cho máu. Vì nó cũng chỉ 1 query có offset nên không cần extend luôn ha. À check nếu XenForo_Model_Like đã extend sẵn rồi thì quăng vô luôn cũng được. Còn chưa extend thì tạo mới hén.

thấy ko có cái extend sẵn nên em tạo Model mới rồi ạ

2020-05-19 11:05 UTC, daohoangson commented
Okie rồi á, đổi cái `content_like_date` về `like_date` cho nó ngắn gọn tí xong anh merge nha. 

Xin cảm ơn.

2020-05-19 13:25 UTC, datbth commented
dạ đã chỉnh. Cám ơn anh

2020-05-19 17:08 UTC, merged