Add rich username response
xfrocks/bdApi pull request #37
Opened 2018-04-16 03:46 UTC by luutruong

2018-04-16 03:56 UTC, daohoangson requested changes
Sửa thêm README luôn nha.

2018-04-16 04:10 UTC, luutruong commented
E đã sửa ở api docs rồi @daohoangson

2018-05-03 03:09 UTC, daohoangson approved these changes

2018-05-03 03:11 UTC, daohoangson requested changes

2018-05-03 03:11 UTC, daohoangson commented on xenforo/library/bdApi/Template/Helper/Core.php
> +        $username = htmlspecialchars($user['username']);
Phải check header trước khi escape bằng `htmlspecialchars` để tránh thay đổi output với các app không hỗ trợ inline style hén.

2018-05-03 08:26 UTC, luutruong commented on xenforo/library/bdApi/Template/Helper/Core.php
> +        $username = htmlspecialchars($user['username']);
Đã sửa anh.

2018-05-16 06:58 UTC, daohoangson approved these changes

2018-05-16 06:59 UTC, daohoangson commented on xenforo/library/bdApi/Template/Helper/Core.php
> +        if (empty($this->_displayStyles) || !XenForo_Application::isRegistered('fc')) {
Sao đoạn này cần check isRegistered `fc` làm gì hén?

2018-05-17 04:23 UTC, luutruong commented on xenforo/library/bdApi/Template/Helper/Core.php
> +        if (empty($this->_displayStyles) || !XenForo_Application::isRegistered('fc')) {
Đề phòng ko có sẵn key đó để xài a. Nhưng chắc hem có cần thiết a nhỉ?

2018-05-17 04:24 UTC, daohoangson commented on xenforo/library/bdApi/Template/Helper/Core.php
> +        if (empty($this->_displayStyles) || !XenForo_Application::isRegistered('fc')) {
Nhưng ở dưới hình như không thấy xài mà.

2018-05-17 04:25 UTC, luutruong commented on xenforo/library/bdApi/Template/Helper/Core.php
> +        if (empty($this->_displayStyles) || !XenForo_Application::isRegistered('fc')) {
Ahihi bốc code ở dưới lên quên chưa check lại chỗ đó :P

2018-05-21 02:44 UTC, merged