Consumer password enhancement
xfrocks/bdApi pull request #45
Opened 2018-06-07 12:45 UTC by luutruong

2018-06-08 01:11 UTC, daohoangson commented
Xin cảm ơn.

2018-06-10 18:03 UTC, daohoangson requested changes

2018-06-10 18:03 UTC, daohoangson commented on xenforo_consumer/library/bdApiConsumer/XenForo/ControllerPublic/Account.php
> +        if ($response instanceof XenForo_ControllerResponse_View
Đoạn này gom vô block ở trên thì gọn hơn hén. Đảo cái if `takeOver.login` vào trong cái if `subView etc.` là gọn.

2018-06-10 18:03 UTC, daohoangson commented on xenforo_consumer/library/bdApiConsumer/XenForo/ControllerPublic/Account.php
> +    public function actionNewPassword()
Xài api external new password cái gì đó thì an toàn hơn. Tránh conflict.

2018-06-10 18:03 UTC, daohoangson commented on xenforo_consumer/library/bdApiConsumer/XenForo/ControllerPublic/Account.php
> +    public function actionConsumerSecurity()
Hai cái action của mình đi cùng nhau nên xài chung preview với nhau luôn cho dễ hiểu nha. Ví dụ cái kia là xxx new password thì cái này là xxx verify chẳng hạn.

2018-06-10 18:03 UTC, daohoangson commented on xenforo_consumer/library/bdApiConsumer/XenForo/ControllerPublic/Account.php
> +            $token = bdApiConsumer_Helper_Api::getAccessTokenFromUsernamePassword($provider, $extraData['username'], $password);
Cho thêm login attempt check hoặc ít nhất là flood check vô đây hén.

2018-06-10 18:03 UTC, daohoangson commented on xenforo_consumer/library/bdApiConsumer/XenForo/ControllerPublic/Account.php
> +            if (!$providerUser) {
Tiện check thì verify luôn cái user lấy về có id khớp với thông tin đã lưu nữa hén.

2018-06-10 18:03 UTC, daohoangson commented on xenforo_consumer/library/bdApiConsumer/XenForo/ControllerPublic/Account.php
> +            $token = bdApiConsumer_Helper_Api::getAccessTokenFromUsernamePassword($provider, $extraData['username'], $password);
Với cả `$extraData.username` có thể không có đâu, nên cần check trước khi xài + hiển thị message không verify được, liên hệ staff.

2018-06-10 18:03 UTC, daohoangson commented on xenforo_consumer/library/bdApiConsumer/addon-bdApiConsumer.xml
> +    <phrase title="bdapi_consumer_or_reset_password_via" version_id="1010100" version_string="1.1.0"><![CDATA[Or reset password via]]></phrase>
Xài placeholder trong phrase luôn nha.

2018-06-10 18:03 UTC, daohoangson commented on xenforo_consumer/library/bdApiConsumer/addon-bdApiConsumer.xml
> +    <phrase title="bdapi_consumer_your_identity_was_verified" version_id="1010100" version_string="1.1.0"><![CDATA[You identity was verified]]></phrase>
You identity **has been** verified.

2018-06-12 02:49 UTC, luutruong commented
@daohoangson Đã commit hết ở trên rồi nhé anh.

2018-06-12 03:05 UTC, daohoangson commented
Xin cảm ơn.


On Tue, Jun 12, 2018 at 9:49 AM Truong Luu <notifications@github.com> wrote:

> @daohoangson <https://github.com/daohoangson> Đã commit hết ở trên rồi
> nhé anh.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/xfrocks/bdApi/pull/45#issuecomment-396448814>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAOm6KfPh6kyg83e246tCz7B0VHGV4Sbks5t7yxLgaJpZM4UeVqo>
> .
>

2018-06-14 07:27 UTC, daohoangson approved these changes

2018-06-14 07:27 UTC, merged