Xf2 api threads
xfrocks/bdApi pull request #62
Opened 2018-07-31 07:43 UTC by luutruong

Added APIs
* POST /threads
* POST /threads/attachments
* DELETE /threads/attachments
* PUT /threads/:threadId
* DELETE /threads/:threadId
* GET /threads/:threadId/followers
* POST /threads/:threadId/followers
* DELETE /threads/:threadId/followers
* GET /threads/followed
* POST /threads/:threadId/poll/votes
* GET /threads/:threadId/poll/results
* GET /threads/new
* GET /threads/recent

2018-08-01 05:44 UTC, daohoangson requested changes

2018-08-01 05:44 UTC, daohoangson commented on Controller/Thread.php
> +            ->define('post_body', 'str', 'contnet of the new thread')
*content

2018-08-01 05:44 UTC, daohoangson commented on Controller/Thread.php
> +            ->define('attachment_hash', 'str', 'a unique hash value')
Chắc làm cái `defineAttachmentHash()` trong Params để tiện xài, đỡ phải gõ đi gõ lại.

2018-08-01 05:44 UTC, daohoangson commented on Controller/Thread.php
> +    public function actionDeleteAttachments()
Bỏ hẳn cái DELETE `/threads/attachments` nha. Implement delete cho attachment theo kiểu tập trung cho dễ.

Ý tưởng là: upload attachment thì vẫn xài POST `/threads/attachments` nhưng attachment trả về sẽ kèm thêm `links.delete` dạng /attachments/123?temp_hash=xxx. Khi nào app muốn delete thì gửi request DELETE lên /attachments/:id là được.

2018-08-01 05:44 UTC, daohoangson commented on Controller/Thread.php
> +            $extraWith[] = 'Watch|' . \XF::visitor()->user_id;
Chắc không cần, `\Xfrocks\Api\XF\Transform\Thread` nó luôn request sẵn Watch|:userId rồi.

2018-08-01 05:44 UTC, daohoangson commented on Controller/Thread.php
> +                        'email' => $thread->Watch[$visitor->user_id]->email_subscribe
Xài `$watch` luôn cho tiện nè.

2018-08-01 05:44 UTC, daohoangson commented on Controller/Thread.php
> +        if ($this->request()->exists('total')) {
Xài `$params` chứ huh?

2018-08-01 05:44 UTC, daohoangson commented on Controller/Thread.php
> +        $params = $this
Cho `$params` lên đầu mỗi method nha.

2018-08-01 05:44 UTC, daohoangson commented on Controller/Thread.php
> +            ->define('data_limit', 'uint')
Ủa tưởng bỏ `data_limit` rồi?

2018-08-01 05:44 UTC, daohoangson commented on Controller/Thread.php
> +            ->define('data_limit', 'uint')
`data_limit`?

2018-08-01 05:44 UTC, daohoangson commented on Controller/Thread.php
> +        $finder->limit($limit);
Đoạn này hình như sai sai? Cái limit phải lấy theo search max results sau đó lưu kết quả vô xf_search. Rồi còn pagenav etc. chứ nhỉ?

2018-08-01 05:44 UTC, daohoangson commented on ControllerPlugin/Attachment.php
> +    public function doDelete($hash, $contentType, $context)
Bỏ cái `doDelete` trong plugin hén, như nói ở trên, gom hết vụ delete attachment vô route attachments và controller Attachment.

2018-08-01 05:44 UTC, daohoangson commented on Transform/TransformContext.php
> +    public function getRootContext()
Chắc là không cho bên ngoài gọi `getRootContext` như thế này, tránh trường hợp bên ngoài lấy root context xong thay đổi giữa chừng thì không biết được. Vậy nên:

1. Bỏ `getRootContext()`
2. Implement thêm `getOnTransformFinderCallbacks()` trả về callbacks từ root
3. Tương tự cho onTransformEntitiesCallbacks với onTransformedCallbacks.

Tóm lại là chỉ cho thằng tạo context sửa mấy cái property đó. Các sub-context chỉ xài thôi, không được sửa.

2018-08-01 06:44 UTC, luutruong commented on Controller/Thread.php
> +        if ($this->request()->exists('total')) {
`params` có check kiểu như thế à a?

2018-08-01 10:12 UTC, daohoangson commented
Ủa, cứ xài $params['total'] thôi không được huh?

2018-08-01 10:12 UTC, daohoangson commented on Controller/Thread.php
> +        if ($this->request()->exists('total')) {
Ủa, cứ xài `$params['total']` thôi không được huh?

2018-08-02 04:41 UTC, daohoangson commented
Bỏ DELETE /threads/attachments với plugin doDelete nhưng chưa implement DELETE /attachments hả chế? Với cả phải trả lại link để delete trong attachment transform nữa.

2018-08-02 04:42 UTC, luutruong commented
Cái đó sẽ chuyển sang branch `/attachments` cho dễ tracking chứ a?

2018-08-02 04:45 UTC, daohoangson commented
Oh okie. Vậy nhớ đừng quên 😂

2018-08-02 04:45 UTC, merged