Xf2 api users
xfrocks/bdApi pull request #63
Opened 2018-08-07 10:27 UTC by luutruong

Added full api users from XF 1 version.

2018-08-08 09:19 UTC, daohoangson requested changes

2018-08-08 09:19 UTC, daohoangson commented on Util/Crypt.php
> +     * Supports both OpenSSL and mcrypt.
Sửa lại mấy cái php doc này đi chế. Chắc xoá hết chỉ để lại param với return thôi.

2018-08-08 09:19 UTC, daohoangson commented on Controller/User.php
> +        $finder->with('Option', true);
Sao lại cần đoạn này hén?

2018-08-08 09:19 UTC, daohoangson commented on Controller/User.php
> +        $allowEmailConfirm = true;
Chắc đổi cái biến này thành `$skipEmailConfirmation` cho nó dễ hiểu huh?

2018-08-08 09:19 UTC, daohoangson commented on Controller/User.php
> +            '_user' => $user->toArray(),
Bỏ `_user` luôn hén. Cái này chủ yếu cho add-on khác override để trả về thêm data, nhưng XF2 có transformer rồi nên không cần nữa.

2018-08-08 09:19 UTC, daohoangson commented on Controller/User.php
> +        $userFields = $this->transformFinderLazily($finder);
Đoạn này hình như chưa chạy hay sao ý nhỉ? Thấy UserField transformer comment out quá trời?

2018-08-08 09:19 UTC, daohoangson commented on Controller/User.php
> +            ->define('avatar', 'file', 'binary data of the avatar');
`defineFile` chứ nhỉ?

2018-08-08 09:19 UTC, daohoangson commented on Controller/User.php
> +        $this->assertRegistrationRequired();
Ủa đoạn này sai sai hén, chắc bug từ XF1.

Check thêm là user chỉ coi được ignored của chính mình hén.

2018-08-08 09:22 UTC, luutruong commented on Controller/User.php
> +        $finder->with('Option', true);
Để chắc chắn user đó valid anh. Kiểu có record bên xf_user nhưng ko có bên các option, profile.

2018-08-08 09:22 UTC, luutruong commented on Controller/User.php
> +        $userFields = $this->transformFinderLazily($finder);
Đúng rồi anh. A kêu refactor cái đoạn này nên vẫn hóng anh.

2018-08-09 03:44 UTC, luutruong commented on Controller/User.php
> +        $this->assertRegistrationRequired();
Cái này luôn chỉ lấy của `$visitor` đó ạ.

2018-08-09 03:45 UTC, daohoangson commented on Controller/User.php
> +        $this->assertRegistrationRequired();
Okie.

2018-08-09 03:45 UTC, daohoangson commented on Controller/User.php
> +        $finder->with('Option', true);
Có cần thiết không hén? Nếu user lỗi thì không lên data thôi còn kệ nó nhỉ?

2018-08-09 03:45 UTC, daohoangson commented on Controller/User.php
> +        $userFields = $this->transformFinderLazily($finder);
Okie, để PR phát.

2018-08-09 04:18 UTC, luutruong commented on Controller/User.php
> +        $finder->with('Option', true);
Vậy thôi bỏ qua cái đó vậy ✌️

2018-08-09 04:36 UTC, daohoangson commented on Controller/User.php
> +        $userFields = $this->transformFinderLazily($finder);
Coi thử cái này nha https://github.com/xfrocks/bdApi/commit/f45cd2f8de6e1f12a83095e0582a7c57e98e1b7d

2018-08-10 05:52 UTC, daohoangson approved these changes

2018-08-10 05:53 UTC, merged