Xf2 api subscriptions
xfrocks/bdApi pull request #73
Opened 2018-09-04 06:57 UTC by luutruong

2018-09-05 08:25 UTC, daohoangson requested changes

2018-09-05 08:25 UTC, daohoangson commented on Listener.php
> +    public static function onEntityUserAlertPostSave(Entity $entity)
Extend entity để override luôn ha, để cái listener nó gọn gàng xíu.

2018-09-05 08:26 UTC, luutruong commented on Listener.php
> +    public static function onEntityUserAlertPostSave(Entity $entity)
Chuyển hết vô extend entity luôn à a?

2018-09-05 08:40 UTC, daohoangson commented on Listener.php
> +    public static function onEntityUserAlertPostSave(Entity $entity)
Uh.

2018-09-05 09:03 UTC, luutruong commented on Listener.php
> +    public static function onEntityUserAlertPostSave(Entity $entity)
E đã sửa lại rồi ạ.

2018-09-06 16:02 UTC, daohoangson requested changes

2018-09-06 16:02 UTC, daohoangson commented on XF/Entity/Thread.php
> +        $subRepo = \XF::repository('Xfrocks\Api:Subscription');
Check option trước khi load repo với delete từ db thì hợp lý hơn nhỉ? Đa số các site sẽ không bật option -> đỡ 1 query.

Với cả chuyển qua xài $this->repo thay vì XF::repo nha.

2018-09-06 16:02 UTC, daohoangson commented on XF/Entity/Thread.php
> +        $subColumn = \XF::options()->bdApi_subscriptionColumnThreadPost;
Nên check cả 2 options rồi mới thêm column vô structure thì an toàn hơn.

2018-09-06 16:02 UTC, daohoangson commented on XF/Entity/UserAlert.php
> +                    $userOptions[$this->alerted_user_id] = $this->db()->fetchOne('
Có cách nào check để lấy từ `UserOption` nếu có sẵn không nhỉ?

2018-09-06 16:02 UTC, daohoangson commented on Repository/PingQueue.php
> +        if ($this->options()->bdApi_pingQueueUseDefer) {
Bỏ option này luôn, XF2 có job manager ngon thế cứ thế xài thôi hén.

2018-09-07 03:32 UTC, luutruong commented
@daohoangson Đã resolved hết rồi đó anh <3

2018-09-07 05:52 UTC, daohoangson commented
Save option vô bị lỗi `Unsupported option bdApi_userNotificationConversation` nè chế.

2018-09-07 06:00 UTC, daohoangson commented
Với cả mấy cái option field chắc không để default, vì upgrade add-on lên vô options bấm save là bị báo lỗi hoài.

2018-09-07 06:19 UTC, daohoangson commented
phpcs reports mấy lỗi nè chế ơi. Cả phpstan nữa. Check lại nhé.

2018-09-07 07:14 UTC, luutruong commented
E đã fix rồi anh @daohoangson

2018-09-07 07:20 UTC, daohoangson commented
Anh có add mấy cái test cho phần này. Có ý tưởng gì test đầy đủ được hết không hén? Đoạn này khá là quan trọng nên cần phải làm chuẩn :-s

2018-09-07 08:06 UTC, merged