Subscription link bug
xfrocks/bdApi pull request #82
Opened 2018-09-28 07:10 UTC by luutruong

2018-09-28 07:42 UTC, daohoangson requested changes

2018-09-28 07:42 UTC, daohoangson commented on Repository/Subscription.php
>          $response->header('Link', sprintf('<%s>; rel=hub', $hubLink));
No overwrite cái này luôn đi chế. Biết đâu có add-on khác nó có header này.

2018-09-28 07:42 UTC, daohoangson commented on _files/tests/api/SubscriptionTest.php
> +        $this->assertArrayHasKey('subscription_callback', $json);
phpunit có kiểu chạy test riêng á, như này không đảm bảo case này luôn chạy đúng à nha.

Tốt nhất là sửa cái test subscribe có sẵn ấy. Sau khi subscribe xong thì GET notifications -> assert có key, blah blah.

Sau đó ngay trong test đấy unsubscribe đi và GET notifications lại -> assert không có key.

2018-09-28 07:42 UTC, daohoangson commented on _files/tests/api/SubscriptionTest.php
> +        $this->assertNotEmpty($link);
Check cụ thể nó phải ra 2 cái rel `hub` với `self` của mình nha chế.

2018-10-01 02:18 UTC, luutruong commented on _files/tests/api/SubscriptionTest.php
> +        $this->assertArrayHasKey('subscription_callback', $json);
GET `notifications` lúc nào chẳng chả về cái key kia a :-?

2018-10-01 02:23 UTC, daohoangson commented on _files/tests/api/SubscriptionTest.php
> +        $this->assertArrayHasKey('subscription_callback', $json);
`subscription_callback` á? Ủa, không có subscription thì không có trả về mà.

2018-10-01 03:00 UTC, merged